### ISSUE TITLE
Server fails to start because of connection error on Go `1.17`

### ISSUE THREAD

**Issue by hallaji** [josa42/coc-go#160]
Hi team 👋🏼

I keep getting a server connection error on Go `1.17`. However, it works fine when I switch to Go `1.16`. Could you advise please.

> Server languageserver.golang failed to start: Error: Connection to server got closed. Server will not be restarted.

Here is the information from `coc.nvim` logs:

```
## versions

vim version: NVIM v0.5.1
node version: v16.5.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /Users/vahid/.vim/plugged/coc.nvim
term: xterm-256color
platform: darwin

## Log of coc.nvim

2021-10-15T13:27:53.185 INFO (pid:1739) [services] - registered service "languageserver.golang"
2021-10-15T13:27:53.192 INFO (pid:1739) [plugin] - coc.nvim 0.0.80-03c9add7cd initialized with node: v16.5.0 after 71ms
2021-10-15T13:27:53.979 INFO (pid:1739) [attach] - receive notification: highlight []
2021-10-15T13:27:57.040 INFO (pid:1739) [services] - golang state change: stopped => starting
2021-10-15T13:27:57.078 INFO (pid:1739) [language-client-index] - Language server "languageserver.golang" started with 2783
2021-10-15T13:27:57.134 INFO (pid:1739) [services] - registered service "go"
2021-10-15T13:27:57.134 INFO (pid:1739) [services] - gopls state change: stopped => starting
2021-10-15T13:27:57.633 INFO (pid:1739) [services] - golang state change: starting => stopped
2021-10-15T13:27:57.633 INFO (pid:1739) [services] - golang state change: stopped => starting
2021-10-15T13:27:57.636 INFO (pid:1739) [language-client-index] - Language server "languageserver.golang" started with 3063
2021-10-15T13:27:57.955 INFO (pid:1739) [services] - golang state change: starting => stopped
2021-10-15T13:27:57.955 INFO (pid:1739) [services] - golang state change: stopped => starting
2021-10-15T13:27:57.958 INFO (pid:1739) [language-client-index] - Language server "languageserver.golang" started with 3315
2021-10-15T13:27:58.268 INFO (pid:1739) [services] - golang state change: starting => stopped
2021-10-15T13:27:58.268 INFO (pid:1739) [services] - golang state change: stopped => starting
2021-10-15T13:27:58.271 INFO (pid:1739) [language-client-index] - Language server "languageserver.golang" started with 3516
2021-10-15T13:27:58.576 INFO (pid:1739) [services] - golang state change: starting => stopped
2021-10-15T13:27:58.577 ERROR (pid:1739) [services] - Server languageserver.golang failed to start: Error: Connection to server got closed. Server will not be restarted.
    at np.handleConnectionClosed (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:223:967)
    at np.handleConnectionClosed (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:223:28612)
    at t (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:223:386)
    at tM.invoke (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:9670)
    at sd.fire (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:10436)
    at bi (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:36:10897)
    at tM.invoke (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:9670)
    at sd.fire (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:10436)
    at ZS.fireClose (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:12716)
    at Socket.<anonymous> (/Users/vahid/.vim/plugged/coc.nvim/build/index.js:35:14275)
2021-10-15T13:27:59.328 INFO (pid:1739) [services] - gopls state change: starting => running
2021-10-15T13:27:59.333 INFO (pid:1739) [services] - service go started
2021-10-15T13:28:07.175 INFO (pid:1739) [attach] - receive notification: showInfo []

```

**Comment by hallaji** [comment]
Go please command `gopls` over `1.17` responds with:

```
gopls
No preset version installed for command gopls
Please install a version by running one of the following:

asdf install golang 1.17.2

or add one of the following versions in your config file
golang 1.16.6
```
