### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by ericuni** [josa42/coc-go#166]
When I run `:CocInstall coc-go`, it responds with the following error, and I have tried serveral times, all the result is the same.
```plain
Install finished
- ✗ coc-go /home/liuqi.victor/opt/node/bin/npm install exited with 1
```

versions
```plain
vim version: VIM - Vi IMproved 8.2 8023640
node version: v16.13.0
coc.nvim version: 0.0.80-03c9add7cd
coc.nvim directory: /data00/home/liuqi.victor/.plugged/coc.nvim
term: dumb
platform: linux
...

go env
```
GO111MODULE="on"
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
```

last part of CocInfo output
```plain
2021-11-24T23:48:06.463 INFO (pid:2285368) [model-installer] - Download progress 100.0%
2021-11-24T23:48:06.463 INFO (pid:2285368) [model-download] - Download completed: https://registry.npmjs.org/coc-go/-/coc-go-1.0.0.tgz
2021-11-24T23:48:06.464 INFO (pid:2285368) [model-download] - Downloaded https://registry.npmjs.org/coc-go/-/coc-go-1.0.0.tgz => /tmp/vCXIsOG/coc-go-XtWMso
2021-11-24T23:48:06.564 INFO (pid:2285368) [model-installer] - Extension download at /tmp/vCXIsOG/coc-go-XtWMso
2021-11-24T23:48:06.566 INFO (pid:2285368) [model-installer] - Installing dependencies by: /home/liuqi.victor/opt/node/bin/npm install --ignore-scripts --no-lockfile --production --legacy-peer-deps.
2021-11-24T23:48:08.287 INFO (pid:2285368) [model-installer] - npm ERR! code ERR_INVALID_URL
npm ERR! Invalid URL

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/liuqi.victor/.npm/_logs/2021-11-24T15_48_08_251Z-debug.log

2021-11-24T23:48:08.288 ERROR (pid:2285368) [extensions] - Error on install coc-go Error: /home/liuqi.victor/opt/node/bin/npm install exited with 1
    at ChildProcess.<anonymous> (/data00/home/liuqi.victor/.plugged/coc.nvim/build/index.js:216:11511)
    at ChildProcess.emit (node:events:390:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
2021-11-24T23:48:08.288 WARN (pid:2285368) [plugin] - Slow action "installExtensions" cost 4695ms
2021-11-24T23:48:12.046 INFO (pid:2285368) [attach] - receive notification: highlight []
2021-11-24T23:48:19.782 INFO (pid:2285368) [attach] - receive notification: showInfo []
```

and the last part of 2021-11-24T15_48_08_251Z-debug.log is as follows
```plain
974 timing idealTree Completed in 1326ms
975 timing command:install Completed in 1338ms
976 verbose stack TypeError [ERR_INVALID_URL]: Invalid URL
976 verbose stack     at new NodeError (node:internal/errors:371:5)
976 verbose stack     at onParseError (node:internal/url:552:9)
976 verbose stack     at new URL (node:internal/url:628:5)
976 verbose stack     at getProxyUri (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:147:53)
976 verbose stack     at getAgent (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/make-fetch-happen/lib/agent.js:20:17)
976 verbose stack     at remoteFetch (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/make-fetch-happen/lib/remote.js:31:17)
976 verbose stack     at cacheFetch (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/make-fetch-happen/lib/cache/index.js:15:28)
976 verbose stack     at async fetch (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/make-fetch-happen/lib/fetch.js:82:7)
976 verbose stack     at async Promise.all (index 8)
976 verbose stack     at async Arborist.[buildDepStep] (/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1046:5)
977 verbose cwd /tmp/vCXIsOG/coc-go-XtWMso
978 verbose Linux 4.19.117.bsk.6-amd64
979 verbose argv "/data00/home/liuqi.victor/opt/node-v16.13.0-linux-x64/bin/node" "/home/liuqi.victor/opt/node/bin/npm" "install" "--ignore-scripts" "--no-lockfile" "--production" "--legacy-peer-deps"
980 verbose node v16.13.0
981 verbose npm  v8.1.0
982 error code ERR_INVALID_URL
983 error Invalid URL
984 verbose exit 1
```

**Comment by josa42** [comment]
Can't reproduce. It's probably unrelated to coc-go
