### ISSUE TITLE
Failed to start: JSON RPC parse error

### ISSUE THREAD

**Issue by Karmenzind** [josa42/coc-go#195]
```
Failed to start:  JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
```
![image](https://user-images.githubusercontent.com/17923071/200767114-e336d466-b026-477b-a3bb-17755a1fafc6.png)

gopls:
(I found this https://github.com/golang/vscode-go/issues/2177 but my gopls is the newest version)

```
➞  gopls version
golang.org/x/tools/gopls v0.10.1
    golang.org/x/tools/gopls@(devel)                                                                                                    
```

CocInfo:

```
## versions

vim version: VIM - Vi IMproved 9.0 9000813
node version: v19.0.0
coc.nvim version: 0.0.82-a7c0900f 2022-11-08 23:10:03 +0800
coc.nvim directory: /home/k/.vim/plugged/coc.nvim
term: tmux
platform: linux

## Log of coc.nvim

2022-11-09T15:22:07.160 INFO (pid:841814) [extension:coc-git] - Looking for git in: git
2022-11-09T15:22:07.168 INFO (pid:841814) [plugin] - coc.nvim initialized with node: v19.0.0 after 67ms
2022-11-09T15:22:07.897 INFO (pid:841814) [services] - LanguageClient gopls state change: stopped => starting
2022-11-09T15:22:07.931 ERROR (pid:841814) [language-client-client] - Server go initialization failed. gh [Error]: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
    at Ie (/home/k/.vim/plugged/coc.nvim/build/index.js:10:233)
    at Ji (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6874)
    at Immediate.<anonymous> (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6721)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32700,
  data: undefined
}
2022-11-09T15:22:07.932 INFO (pid:841814) [services] - LanguageClient gopls state change: starting => stopped
2022-11-09T15:22:07.932 ERROR (pid:841814) [services] - Server go failed to start: gh [Error]: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
    at Ie (/home/k/.vim/plugged/coc.nvim/build/index.js:10:233)
    at Ji (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6874)
    at Immediate.<anonymous> (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6721)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32700,
  data: undefined
}
2022-11-09T15:22:08.159 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:22:13.019 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:05.960 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:06.366 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:16.449 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:24.801 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:35.287 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:45.995 INFO (pid:841814) [attach] - receive notification: installExtensions [ 'coc-go' ]
2022-11-09T15:25:46.326 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:47.128 INFO (pid:841814) [extension-installer] - Fetched info of coc-go {
  'dist.tarball': 'http://<localregistry>/artifactory/api/npm/npm-hiktest/coc-go/-/coc-go-1.3.0.tgz',
  'engines.coc': '^0.0.80',
  version: '1.3.0',
  name: 'coc-go'
}
2022-11-09T15:25:47.240 INFO (pid:841814) [model-download] - Download completed: URL {
  href: 'http://<localregistry>/artifactory/api/npm/npm-hiktest/coc-go/-/coc-go-1.3.0.tgz',
  origin: 'http://<localregistry>',
  protocol: 'http:',
  username: '',
  password: '',
  host: '<localregistry>',
  hostname: '<localregistry>',
  port: '',
  pathname: '/artifactory/api/npm/npm-hiktest/coc-go/-/coc-go-1.3.0.tgz',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
2022-11-09T15:25:47.241 INFO (pid:841814) [model-download] - Downloaded http://<localregistry>/artifactory/api/npm/npm-hiktest/coc-go/-/coc-go-1.3.0.tgz => /home/k/.config/coc/extensions/node_modules/coc-go-5065b879-a6f0-4501-a50b-1ac94a6f84a8
2022-11-09T15:25:47.815 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:49.263 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:51.166 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:25:51.504 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:26:03.858 WARN (pid:841814) [plugin] - Slow action "installExtensions" cost 17863ms
2022-11-09T15:26:03.862 INFO (pid:841814) [services] - LanguageClient gopls state change: stopped => starting
2022-11-09T15:26:03.885 ERROR (pid:841814) [language-client-client] - Server go initialization failed. gh [Error]: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
    at Ie (/home/k/.vim/plugged/coc.nvim/build/index.js:10:233)
    at Ji (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6874)
    at Immediate.<anonymous> (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6721)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32700,
  data: undefined
}
2022-11-09T15:26:03.886 INFO (pid:841814) [services] - LanguageClient gopls state change: starting => stopped
2022-11-09T15:26:03.886 ERROR (pid:841814) [services] - Server go failed to start: gh [Error]: JSON RPC parse error: json: cannot unmarshal number into Go struct field RenameClientCapabilities.capabilities.textDocument.rename.prepareSupportDefaultBehavior of type bool: JSON RPC parse error
    at Ie (/home/k/.vim/plugged/coc.nvim/build/index.js:10:233)
    at Ji (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6874)
    at Immediate.<anonymous> (/home/k/.vim/plugged/coc.nvim/build/index.js:9:6721)
    at process.processImmediate (node:internal/timers:471:21) {
  code: -32700,
  data: undefined
}
2022-11-09T15:26:09.183 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:26:09.963 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:26:10.825 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:28.478 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:31.203 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:31.785 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:32.185 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:33.045 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:33.047 INFO (pid:841814) [attach] - Request action: hasProvider [ 'hover' ]
2022-11-09T15:28:33.349 INFO (pid:841814) [attach] - receive notification: highlight []
2022-11-09T15:28:42.697 INFO (pid:841814) [attach] - receive notification: showInfo []


```

**Comment by jensenojs** [comment]
same problem

**Comment by jensenojs** [comment]
@Karmenzind i don't know what happends, but i successfully install coc-go with just simply retry

**Comment by Karmenzind** [comment]
@jensenojs I've removed and reinstalled coc-go for many times but it still raised JSON RPC error.

**Comment by Karmenzind** [comment]
@jensenojs  It finally worked after I put these lines into coc-settings:
```json
  "languageserver": {
    "go": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".svn/"],
      "filetypes": ["go"],
      "initializationOptions": {
        "usePlaceholders": true
      }
    }
  },

```
But these seems to be coc-go's default configuration. I still have no idea what happened.
