### ISSUE TITLE
Trouble with the $HOME/.config/coc/extensions/coc-go-data/bin directory

### ISSUE THREAD

**Issue by st3fan** [josa42/coc-go#51]
I added the `coc-go` extension by calling `:CocInstall coc-go`. After opening a `.go` file, I am greeted with the following error:

```
  1 vim version: NVIM v0.4.2
  2 node version: v8.10.0
  3 coc.nvim version: 0.0.74-9796d96780
  4 term: screen-256color
  5 platform: linux
  6
  7 ## Messages
  8 [coc.nvim] error: UnhandledRejection: ENOENT: no such file or directory, mkdir '/home/stefan/.config/coc/extensions/coc-go-data/bin'
  9 Error: ENOENT: no such file or directory, mkdir '/home/stefan/.config/coc/extensions/coc-go-data/bin'
 10     at Object.fs.mkdirSync (fs.js:885:18)
 11     at Promise (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:19:26)
 12     at new Promise (<anonymous>)
 13     at Object.<anonymous> (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:18:16)
 14     at Generator.next (<anonymous>)
 15     at /home/stefan/.config/coc/extensions/node_modules/coc-go/node_modules/tslib/tslib.js:110:75
 16     at new Promise (<anonymous>)
 17     at Object.__awaiter (/home/stefan/.config/coc/extensions/node_modules/coc-go/node_modules/tslib/tslib.js:106:16)
 18     at Object.configDir (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:12:20)
 19     at Object.<anonymous> (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:35:51)
```

I manually ran a `mkdir -p $HOME/.config/coc/extensions/coc-go-data/bin` but that did not do the trick. The directory was properly created, but now things are failing because the directory already exists ...

```
  1
  2 vim version: NVIM v0.4.2
  3 node version: v8.10.0
  4 coc.nvim version: 0.0.74-9796d96780
  5 term: screen-256color
  6 platform: linux
  7
  8 ## Messages
  9 [coc.nvim] error: UnhandledRejection: EEXIST: file already exists, mkdir '/home/stefan/.config/coc/extensions/coc-go-data/bin'
 10 Error: EEXIST: file already exists, mkdir '/home/stefan/.config/coc/extensions/coc-go-data/bin'
 11     at Object.fs.mkdirSync (fs.js:885:18)
 12     at Promise (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:19:26)
 13     at new Promise (<anonymous>)
 14     at Object.<anonymous> (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:18:16)
 15     at Generator.next (<anonymous>)
 16     at /home/stefan/.config/coc/extensions/node_modules/coc-go/node_modules/tslib/tslib.js:110:75
 17     at new Promise (<anonymous>)
 18     at Object.__awaiter (/home/stefan/.config/coc/extensions/node_modules/coc-go/node_modules/tslib/tslib.js:106:16)
 19     at Object.configDir (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:12:20)
 20     at Object.<anonymous> (/home/stefan/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:35:51)
```

I'm not sure how to get past this. Is this a bug or is there something odd with my install?

**Comment by st3fan** [comment]
I worked around this by wrapping the call to `mkdirSync` in a `existsSync`

```
        return new Promise((resolve) => {
            if (!fs_1.default.existsSync(dir)) {
              fs_1.default.mkdirSync(dir, { recursive: true });
            }
            resolve(dir);
        });
```

It got me past installation issues but I bet this is a bad hack since this JS looks like it is transpiled?
