### ISSUE TITLE
UnhandledRejection: ENOENT: no such file or directory 

### ISSUE THREAD

**Issue by quanlou** [josa42/coc-go#62]
just try coc-go after installing by `:CocInstall coc-go`
it seem like the #29 didn't fix the problem completely 
- os: macOS Mojave
- error stack trace messages:

```[coc.nvim] error: UnhandledRejection: ENOENT: no such file or directory, mkdir '/Users/quan.luu/.config/coc/extensions/coc-go-data/bin'
Error: ENOENT: no such file or directory, mkdir '/Users/quan.luu/.config/coc/extensions/coc-go-data/bin'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Promise (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:19:26)
    at new Promise (<anonymous>)
    at Object.configDir (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:17:12)
    at goBinPath (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:32:47)
    at goBinExists (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:47:23)
    at Object.installGoBin (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:13:25)
    at registerTest (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/extension.js:55:24)
    at Object.activate (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/extension.js:19:5)
    at Object.activate (/Users/quan.luu/.config/nvim/plugged/coc.nvim/build/index.js:36191:57)
[coc.nvim] error: UnhandledRejection: ENOENT: no such file or directory, mkdir '/Users/quan.luu/.config/coc/extensions/coc-go-data/bin'
Error: ENOENT: no such file or directory, mkdir '/Users/quan.luu/.config/coc/extensions/coc-go-data/bin'
    at Object.fs.mkdirSync (fs.js:885:18)
    at Promise (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:19:26)
    at new Promise (<anonymous>)
    at Object.configDir (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/config.js:17:12)
    at goBinPath (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:32:47)
    at goBinExists (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:47:23)
    at Object.installGoBin (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/utils/tools.js:13:25)
    at registerTags (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/extension.js:61:24)
    at Object.activate (/Users/quan.luu/.config/coc/extensions/node_modules/coc-go/lib/extension.js:20:5)
    at Object.activate (/Users/quan.luu/.config/nvim/plugged/coc.nvim/build/index.js:36191:57)```

**Comment by josa42** [comment]
Unfortunately, I couldn't find a way to reproduce this issue. A reliable reproduction would be appreciated.

**Comment by luisdavim** [comment]
does the folder `~/.config/coc/extensions` exist in your computer? Maybe this extension is not creating it if it's missing before trying to create the `coc-go-data` folder.
Another potential problem is that the go tools failed to install and the bin folder was never created because of that, did you get any errors during the installation?

**Comment by quanlou** [comment]
I'm still able to reproduce this bug, the folder `~/.config/coc/extensions` exists, I think I didn't face any errors during the installation  
<img width="956" alt="Screen Shot 2020-03-11 at 10 13 32 PM" src="https://user-images.githubusercontent.com/9912470/76432540-b2675b00-63e5-11ea-9448-36d87bb9e372.png">

**Comment by Paryz** [comment]
i've added folder `coc-go-data` and `bin` inside it and it started working correctly, probably some permission problem

**Comment by josa42** [comment]
Seems to be a bug in nodejs 😐 https://github.com/nodejs/node/issues/27293
