### ISSUE TITLE
client coc abnormal exit with: 7

### ISSUE THREAD

**Issue by luisdavim** [josa42/coc-go#92]
Since I've updated to the latest version of `coc-go` whenever I open a `go` file I get a red bar saying `client coc abnormal exit with: 7`. 

The output of `CoCInfo`

```
## versions

vim version: VIM - Vi IMproved 8.2 8021150
node version: v14.5.0
coc.nvim version: 0.0.78-449dcad0b2
coc.nvim directory: ~/.vim/bundle/coc.nvim
term: dumb
platform: darwin

## Output channel: explorer


## Output channel: git

Looking for git in: git
> git rev-parse --show-toplevel
resolved root: ~/workingCopies/src/github.com/luisdavim/dotfiles

## Output channel: prettier


## Output channel: snippets

[Info 20:10:24] Using ultisnips directories: UltiSnips gosnippets/UltiSnips ~/.config/coc/ultisnips
[Info 20:10:24] Using ultisnips python command: pyx

## Output channel: highlight

[Info  - 20:10:24] Highlight server running in node v14.5.0
```

**Comment by luisdavim** [comment]
I was able to track down the issue and it seems a duplicate of #90 and #91 

```[coc.nvim]: UnhandledRejection: TypeError: Cannot read property 'workspaceFolders' of undefinedable)"}}return err.stack.toString()}function stackTra
[coc.nvim]: UnhandledRejection: TypeError: Cannot read property 'workspaceFolders' of undefinedturn demangleAll(js)}var buffer,HEAP8,HEAPU8,HEAP16,H
[coc.nvim]: Uncaught exception: Error: process.exit() is not allowed in extension sandboxHEAP8=new Int8Array(buffer);Module["HEAP16"]=HEAP16=new Int
[coc.nvim]: Uncaught exception: Error: process.exit() is not allowed in extension sandboxw Uint8Array(buffer);Module["HEAPU16"]=HEAPU16=new Uint16Ar
[coc.nvim]:     at process.exit (~/.vim/bundle/coc.nvim/build/index.js:54045:15)loat32Array(buffer);Module["HEAPF64"]=HEAPF64=new Float
[coc.nvim]:     at process.exit (~/.vim/bundle/coc.nvim/build/index.js:54045:15)DYNAMIC_BASE,DYNAMICTOP_PTR;STATIC_BASE=STATICTOP=STACK
[coc.nvim]:     at process.<anonymous> (~/.config/coc/extensions/node_modules/coc-sql/lib/index.js:153556:2960)nlarge memory arrays. Ei
[coc.nvim]:     at process.<anonymous> (~/.config/coc/extensions/node_modules/coc-sql/lib/index.js:153556:2960)MEMORY_GROWTH=1  which a
[coc.nvim]:     at process.emit (events.js:326:22)some optimizations, (3) set Module.TOTAL_MEMORY to a higher value before the program runs, or (4)
[coc.nvim]:     at process.emit (events.js:326:22)his abort, compile with  -s ABORTING_MALLOC=0 ")}function enlargeMemory(){abortOnCannotGrowMemory(
[coc.nvim]:     at processPromiseRejections (internal/process/promises.js:245:33)EMORY"]||16777216;if(TOTAL_MEMORY<TOTAL_STACK)err("TOTAL_MEMORY sho
[coc.nvim]:     at processPromiseRejections (internal/process/promises.js:245:33)")");if(Module["buffer"]){buffer=Module["buffer"]}else{{buffer=new
[coc.nvim]:     at processTicksAndRejections (internal/process/task_queues.js:94:32) getTotalMemory(){return TOTAL_MEMORY}function callRuntimeCallba
[coc.nvim]:     at processTicksAndRejections (internal/process/task_queues.js:94:32)llback=="function"){callback();continue}var func=callback.func;i
[coc.nvim]: ~/.config/coc/extensions/node_modules/coc-sql/lib/index.js:153556le["dynCall_vi"](func,callback.arg)}}else{func(callback.ar
[coc.nvim]: ~/.config/coc/extensions/node_modules/coc-sql/lib/index.js:153556;var __ATEXIT__=[];var __ATPOSTRUN__=[];var runtimeInitial
[coc.nvim]: var Module=typeof Module!=="undefined"?Module:{};var Module={print:(function(text){console.log("stdout: "+text)}),printErr:(func.../////
```

**Comment by luisdavim** [comment]
#89 seems to fix the issue.
